version: '3.4'

services:
  api:
    image: api
    container_name: api
    build: .
    environment:
      - PORT=80
      - JDBCURL=jdbc:postgresql://postgres:5432
    ports:
      - "8000:80"
    depends_on:
      - postgres

  postgres:
    image: postgres:16.2-alpine3.19
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: ApiKtor
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  pgadmin:
    image: dpage/pgadmin4:8.0
    container_name: pdadmin
    restart: always
    environment:
      - PGADMIN_DEFAULT_EMAIL=user@email.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin

volumes:
  postgres_data:
  pgadmin_data: